### PR TITLE
GLC fork, many changes from upstream GameHub

### PR DESCRIPTION
**Pull request by Nutzzz**
See README.md for description.

I'm sorry that this is an omnibus commit.  I really liked the idea of a console-based game launcher, so I started making changes for my personal purposes without any real intention to distribute it, but I got inspired and the thing got away from me.  This request is more a notification that you might find some interesting ideas in here rather than a serious expectation that you'd accept the request as-is wholesale, especially as:
- I'm the first to admit I'm not the best programmer
- I tore up the DockConsole/ConsoleHelper subclass (to the extent that might be important for your future plans)
- There's a bunch of half-done stuff
- The current state is a bit messy, even for me

If you're inspired to pick the project back up, let me know if you'd like my help to start peeling off any of the added features as individual pull requests to your repo.  [If I had to pick one must-have, I'd suggest scanning Epic Games using the json .item files. EDIT: ...and I recently committed something to my fork that does something similar with Steam .acf files.]

### CODE REVIEW

**Comment by Solaire** [comment]
Hi there,
Sorry for the delay, I didn't see any notifications on pull requests, I guess it's my fault for not watching my own repos. I can see that this is a pretty massive PR but I am quite confident that I will be able to review it by Monday.

Honestly, I am quite surprised to see that someone found the project and decided to improve it; I wrote the thing as a result of frustrations with icons and folders and I wasn't aware of any good light-weight launchers like PlayNite or the Linux GameHub.

**Comment by Solaire** [comment]
Also to address your comment about peeling off the features. I wouldn't worry about that. I'll have a look through the code and once it goes on master, I'll just stick another release version

**Comment by Nutzzz** [comment]
:-)  I'm glad you're interested in continuing the project.  In terms of peeling off features, I had the idea you might not like where I was going with some of my changes, especially as it becomes less lightweight.  See, e.g.: https://github.com/Nutzzz/GLC/issues/1#issuecomment-841797148

**Comment by Solaire** [comment]
Damn. I like this a lot! This will be a great addition to the repo

I was going to re-implement the thing in C++ to improve performance, remove any .NET dependencies and address the fact it only works with certain shells, but I never had the time to work on the app due to work and other projects (and after a certain point I was comfortable with what I have written, speaking purely of the functionality it offers). But I think a complete re-implementation is not worth it at this point (maybe at some point in the future, if I ever want to go for Linux).

As for the future, I thing there is no point making a proper GUI application (there's already PlayNite for that sort of thing), and I do have a lit of ideas:
- Use a lightweight database instead of a json file (you mentioned that I believe in your TODOs?). Json is cool and all but you can't simply edit a single block/object without having to read and write the whole file. I think C#/.NET has a built-in one but we can always use SQLite.
- Connecting to all game clients like steam, gog, etc - this would allow the user to see all games on their account and install any games they want. Obviously it's a long-shot but I think playnite does something similar (I am not 100% certain)

I have had a look at your TODO lists. What I will do is take them and add them to issues as feature requests

Again, many thanks for your work :)

**Pull request merged**
