### PR TITLE
Switch to .ini; File browser for export shortcuts

### PR DESCRIPTION
**Pull request by Nutzzz**
* Switch config items from .json to .ini
* First pass at new feature: Export all shortcuts for a platform to a given folder

### CODE REVIEW

**Review by Solaire — DISMISSED** [review]

**Comment by Solaire** [comment]
Sorry for the delay. Personal and work stuff got in the way, didn't have opportunity to check the repo or work on it.
@Nutzzz Looks good, but there is a merge conflict. Can you resolve it?

**Comment by Nutzzz** [comment]
Sorry, was behind.  [And no worries for the delay.]
EDIT: Actually, this won't compile because the .ini change messed up Converter.cs.  Give me a bit.

**Review by Solaire — DISMISSED** [review]

**Comment by Solaire** [comment]
Okay, let me know when it's ready again and I'll put it on master

**Comment by Nutzzz** [comment]
And now sorry for my delay. 😄

**Review by Solaire — APPROVED** [review]

**Pull request merged**
